/*
   This file has been generated by IDA.
   It contains local type definitions from
   the type library 'critical_heap'
*/

#define __int8 char
#define __int16 short
#define __int32 int
#define __int64 long long

/* 1 */
struct __attribute__((aligned(8))) Elf64_Sym
{
  unsigned __int32 st_name;
  unsigned __int8 st_info;
  unsigned __int8 st_other;
  unsigned __int16 st_shndx;
  unsigned __int64 st_value;
  unsigned __int64 st_size;
};

/* 2 */
struct Elf64_Rela
{
  unsigned __int64 r_offset;
  unsigned __int64 r_info;
  __int64 r_addend;
};

/* 3 */
struct Elf64_Dyn
{
  unsigned __int64 d_tag;
  unsigned __int64 d_un;
};

/* 4 */
struct __va_list_tag
{
  unsigned int gp_offset;
  unsigned int fp_offset;
  void *overflow_arg_area;
  void *reg_save_area;
};

/* 5 */
typedef __va_list_tag gcc_va_list[1];

/* 6 */
struct NormalHeap
{
  char *heapname;
  __int64 isused;
  __int64 magicx13371337;
  char buf[40];
  __int64 zero;
};

/* 7 */
struct SystemHeap
{
  char *heapname;
  __int64 isused;
  __int64 magicx48694869;
  char *current_dir_name;
  char *secret_of_heap;
  char *user_of_heap;
  char *name_of_heap;
  __int32 rand_num;
  __int32 unused32;
  __int64 unused64;
};

/* 8 */
struct ClockHeap
{
  char *heapname;
  __int64 isused;
  __int64 magicxDEADBEEF;
  struct tm *tmtime;
  __int32 year;
  __int32 month;
  __int32 day;
  __int32 hour;
  __int32 minute;
  __int32 seconds;
  __int64 unused[2];
};

/* 9 */
struct CustomHeap
{
  char *heapname;
  __int64 isused;
  __int64 magic;
  __int64 unused[6];
};

